In [1]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('cloud_customer_churn (1).csv')
df.head(20)

,Customer_ID,Monthly_Cloud_Spend,Compute_Usage_Hours,Storage_GB,Support_Tickets,Account_Age_Months,Contract_Type,Region,Services_Used,Downtime_Hours,Auto_Renew,Customer_Satisfaction,Churn
0,CUST_0001,427.54,337.9,435.3,2,35,Monthly,Middle East,6,2.47,Yes,5.0,Yes
1,CUST_0002,293.66,197.6,403.6,0,5,Monthly,Asia Pacific,7,0.57,Yes,1.0,No
2,CUST_0003,276.27,278.5,437.8,1,22,Two-Year,Asia Pacific,8,0.78,No,5.0,No
3,CUST_0004,276.28,77.0,458.3,3,57,Monthly,North America,7,0.81,Yes,4.0,No
4,CUST_0005,739.94,400.6,101.0,3,47,Annual,Asia Pacific,1,0.05,Yes,1.0,No
5,CUST_0006,495.17,384.7,209.1,4,54,Two-Year,Europe,8,0.83,Yes,1.0,No
6,CUST_0007,236.54,258.3,363.3,0,3,Monthly,Asia Pacific,6,3.25,Yes,4.0,No
7,CUST_0008,438.53,230.4,96.5,3,53,Monthly,Middle East,1,4.55,Yes,4.0,No
8,CUST_0009,369.80,199.0,395.6,1,31,Annual,Europe,5,1.46,Yes,4.0,No
9,CUST_0010,72.44,352.1,454.4,2,69,Two-Year,North America,4,1.22,Yes,5.0,No


In [4]:
df.shape

(600, 13)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Customer_ID            600 non-null    object 
 1   Monthly_Cloud_Spend    588 non-null    float64
 2   Compute_Usage_Hours    600 non-null    float64
 3   Storage_GB             588 non-null    float64
 4   Support_Tickets        600 non-null    int64  
 5   Account_Age_Months     600 non-null    int64  
 6   Contract_Type          600 non-null    object 
 7   Region                 600 non-null    object 
 8   Services_Used          600 non-null    int64  
 9   Downtime_Hours         600 non-null    float64
 10  Auto_Renew             600 non-null    object 
 11  Customer_Satisfaction  588 non-null    float64
 12  Churn                  600 non-null    object 
dtypes: float64(5), int64(3), object(5)
memory usage: 61.1+ KB


In [6]:
df.isnull().sum()

Customer_ID               0
Monthly_Cloud_Spend      12
Compute_Usage_Hours       0
Storage_GB               12
Support_Tickets           0
Account_Age_Months        0
Contract_Type             0
Region                    0
Services_Used             0
Downtime_Hours            0
Auto_Renew                0
Customer_Satisfaction    12
Churn                     0
dtype: int64

In [8]:
df["Churn"].value_counts()

Churn
No     473
Yes    127
Name: count, dtype: int64

In [10]:
numeric_features = [
    "Monthly_Cloud_Spend",
    "Compute_Usage_Hours",
    "Storage_GB",
    "Support_Tickets",
    "Account_Age_Months",
    "Services_Used",
    "Downtime_Hours",
    "Customer_Satisfaction"
]

categorical_features = [
    "Contract_Type",
    "Region",
    "Auto_Renew"
]

In [12]:
for column in df.columns:
    print(column)
    print(df[column].value_counts())
    print()

Customer_ID
Customer_ID
CUST_0001    1
CUST_0395    1
CUST_0397    1
CUST_0398    1
CUST_0399    1
            ..
CUST_0201    1
CUST_0202    1
CUST_0203    1
CUST_0204    1
CUST_0600    1
Name: count, Length: 600, dtype: int64

Monthly_Cloud_Spend
Monthly_Cloud_Spend
278.62    2
507.35    2
305.63    2
360.08    2
115.84    2
         ..
198.85    1
279.97    1
519.21    1
316.39    1
572.17    1
Name: count, Length: 582, dtype: int64

Compute_Usage_Hours
Compute_Usage_Hours
132.4    3
90.5     3
144.0    2
163.2    2
156.5    2
        ..
115.7    1
254.1    1
414.9    1
372.2    1
412.7    1
Name: count, Length: 559, dtype: int64

Storage_GB
Storage_GB
490.2     2
290.4     2
529.4     2
495.7     2
413.0     2
         ..
220.1     1
1192.0    1
603.9     1
132.0     1
823.6     1
Name: count, Length: 574, dtype: int64

Support_Tickets
Support_Tickets
1    152
2    141
3    136
4     68
0     66
5     25
6     12
Name: count, dtype: int64

Account_Age_Months
Account_Age_Months
25  

In [13]:
X = df.drop(columns=["Customer_ID", "Churn"])
y = df["Churn"]

In [14]:

y.shape

(600,)

In [15]:
X.shape

(600, 11)

In [16]:
for column in df.columns:
    print(column, df[column].nunique())

Customer_ID 600
Monthly_Cloud_Spend 582
Compute_Usage_Hours 559
Storage_GB 574
Support_Tickets 7
Account_Age_Months 72
Contract_Type 3
Region 4
Services_Used 8
Downtime_Hours 333
Auto_Renew 2
Customer_Satisfaction 5
Churn 2


In [17]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [18]:
print(X_train.shape)
print(X_test.shape)

print(y_train.value_counts())
print(y_test.value_counts())

(480, 11)
(120, 11)
Churn
No     378
Yes    102
Name: count, dtype: int64
Churn
No     95
Yes    25
Name: count, dtype: int64


In [19]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer

In [20]:
numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

In [21]:
categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

In [22]:
preprocessor = ColumnTransformer([
    ("num", numeric_pipeline, numeric_features),
    ("cat", categorical_pipeline, categorical_features)
])

In [23]:
from sklearn.ensemble import RandomForestClassifier

model_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", RandomForestClassifier(
        n_estimators=200,
        random_state=42,
        class_weight="balanced"
    ))
])

Because churn is imbalanced, class_weight="balanced" helps the model pay more attention to the smaller Yes class.

In [24]:
model_pipeline.fit(X_train, y_train)

,steps,"[('preprocessor', ...), ('model', ...)]"
,transform_input,None
,memory,None
,verbose,False
,transformers,"[('num', ...), ('cat', ...)]"
,remainder,'drop'
,sparse_threshold,0.3
,n_jobs,None
,transformer_weights,None
,verbose,False
,verbose_feature_names_out,True


In [25]:
y_pred = model_pipeline.predict(X_test)

In [26]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print("Accuracy:", accuracy_score(y_test, y_pred))
print()

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print()

print("Classification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 0.775

Confusion Matrix:
[[93  2]
 [25  0]]

Classification Report:
              precision    recall  f1-score   support

          No       0.79      0.98      0.87        95
         Yes       0.00      0.00      0.00        25

    accuracy                           0.78       120
   macro avg       0.39      0.49      0.44       120
weighted avg       0.62      0.78      0.69       120



In [27]:
from sklearn.linear_model import LogisticRegression

logistic_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", LogisticRegression(
        class_weight="balanced",
        max_iter=1000,
        random_state=42
    ))
])

logistic_pipeline.fit(X_train, y_train)

y_pred_log = logistic_pipeline.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred_log))
print()
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_log))
print()
print("Classification Report:")
print(classification_report(y_test, y_pred_log))

Accuracy: 0.675

Confusion Matrix:
[[64 31]
 [ 8 17]]

Classification Report:
              precision    recall  f1-score   support

          No       0.89      0.67      0.77        95
         Yes       0.35      0.68      0.47        25

    accuracy                           0.68       120
   macro avg       0.62      0.68      0.62       120
weighted avg       0.78      0.68      0.70       120



In [28]:
from sklearn.metrics import roc_auc_score

rf_prob = model_pipeline.predict_proba(X_test)[:, 1]
log_prob = logistic_pipeline.predict_proba(X_test)[:, 1]

rf_auc = roc_auc_score(y_test, rf_prob)
log_auc = roc_auc_score(y_test, log_prob)

print("Random Forest ROC-AUC:", rf_auc)
print("Logistic Regression ROC-AUC:", log_auc)

Random Forest ROC-AUC: 0.7067368421052632
Logistic Regression ROC-AUC: 0.7553684210526316


In [29]:
from sklearn.metrics import precision_score, recall_score, f1_score

for threshold in [0.3, 0.4, 0.5, 0.6, 0.7]:

    y_pred_threshold = np.where(
        log_prob >= threshold,
        "Yes",
        "No"
    )

    precision = precision_score(
        y_test,
        y_pred_threshold,
        pos_label="Yes"
    )

    recall = recall_score(
        y_test,
        y_pred_threshold,
        pos_label="Yes"
    )

    f1 = f1_score(
        y_test,
        y_pred_threshold,
        pos_label="Yes"
    )

    print(
        "Threshold:", threshold,
        "| Precision:", round(precision, 3),
        "| Recall:", round(recall, 3),
        "| F1:", round(f1, 3)
    )

Threshold: 0.3 | Precision: 0.286 | Recall: 0.88 | F1: 0.431
Threshold: 0.4 | Precision: 0.328 | Recall: 0.84 | F1: 0.472
Threshold: 0.5 | Precision: 0.354 | Recall: 0.68 | F1: 0.466
Threshold: 0.6 | Precision: 0.406 | Recall: 0.52 | F1: 0.456
Threshold: 0.7 | Precision: 0.52 | Recall: 0.52 | F1: 0.52


In [30]:
final_threshold = 0.7

y_pred_final = np.where(
    log_prob >= final_threshold,
    "Yes",
    "No"
)

print(confusion_matrix(y_test, y_pred_final))
print()
print(classification_report(y_test, y_pred_final))

[[83 12]
 [12 13]]

              precision    recall  f1-score   support

          No       0.87      0.87      0.87        95
         Yes       0.52      0.52      0.52        25

    accuracy                           0.80       120
   macro avg       0.70      0.70      0.70       120
weighted avg       0.80      0.80      0.80       120



In [31]:
from sklearn.model_selection import cross_val_score

cv_scores = cross_val_score(
    logistic_pipeline,
    X_train,
    y_train,
    cv=5,
    scoring="roc_auc"
)

print("CV ROC-AUC scores:", cv_scores)
print("Mean CV ROC-AUC:", cv_scores.mean())
print("Std CV ROC-AUC:", cv_scores.std())

CV ROC-AUC scores: [0.84144737 0.78684211 0.80328947 0.70730159 0.70603175]
Mean CV ROC-AUC: 0.7689824561403509
Std CV ROC-AUC: 0.0538784252094967


In [32]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    "model__C": [0.01, 0.1, 1, 10, 100]
}

grid_search = GridSearchCV(
    logistic_pipeline,
    param_grid=param_grid,
    cv=5,
    scoring="roc_auc",
    n_jobs=-1
)

grid_search.fit(X_train, y_train)

print("Best C:", grid_search.best_params_)
print("Best CV ROC-AUC:", grid_search.best_score_)

Best C: {'model__C': 0.1}
Best CV ROC-AUC: 0.7691904761904762


In [33]:
best_model = grid_search.best_estimator_

best_prob = best_model.predict_proba(X_test)[:, 1]

print(
    "Test ROC-AUC:",
    roc_auc_score(y_test, best_prob)
)

Test ROC-AUC: 0.7536842105263157


In [34]:
import joblib

best_model = grid_search.best_estimator_

joblib.dump(
    best_model,
    "cloud_churn_pipeline.pkl"
)

print("Pipeline saved successfully.")

Pipeline saved successfully.


In [35]:
loaded_model = joblib.load("cloud_churn_pipeline.pkl")

sample_predictions = loaded_model.predict(X_test.head())

print(sample_predictions)

['Yes' 'No' 'Yes' 'No' 'Yes']


In [36]:
loaded_prob = loaded_model.predict_proba(X_test.head())[:, 1]

loaded_pred_07 = np.where(
    loaded_prob >= 0.7,
    "Yes",
    "No"
)

print(loaded_pred_07)

['No' 'No' 'Yes' 'No' 'Yes']


In [37]:
from sklearn.model_selection import train_test_split

X_train_val, X_test, y_train_val, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [38]:
X_train, X_val, y_train, y_val = train_test_split(
    X_train_val,
    y_train_val,
    test_size=0.25,
    random_state=42,
    stratify=y_train_val
)


In [39]:
best_model = Pipeline([
    ("preprocessor", preprocessor),
    ("model", LogisticRegression(
        C=0.1,
        class_weight="balanced",
        max_iter=1000,
        random_state=42
    ))
])

best_model.fit(X_train, y_train)

,steps,"[('preprocessor', ...), ('model', ...)]"
,transform_input,None
,memory,None
,verbose,False
,transformers,"[('num', ...), ('cat', ...)]"
,remainder,'drop'
,sparse_threshold,0.3
,n_jobs,None
,transformer_weights,None
,verbose,False
,verbose_feature_names_out,True


In [40]:
val_prob = best_model.predict_proba(X_val)[:, 1]

In [41]:
from sklearn.metrics import precision_score, recall_score, f1_score
import numpy as np

for threshold in np.arange(0.3, 0.81, 0.05):

    val_pred = np.where(
        val_prob >= threshold,
        "Yes",
        "No"
    )

    precision = precision_score(
        y_val,
        val_pred,
        pos_label="Yes"
    )

    recall = recall_score(
        y_val,
        val_pred,
        pos_label="Yes"
    )

    f1 = f1_score(
        y_val,
        val_pred,
        pos_label="Yes"
    )

    print(
        round(threshold, 2),
        "Precision:", round(precision, 3),
        "Recall:", round(recall, 3),
        "F1:", round(f1, 3)
    )

0.3 Precision: 0.261 Recall: 0.92 F1: 0.407
0.35 Precision: 0.286 Recall: 0.88 F1: 0.431
0.4 Precision: 0.303 Recall: 0.8 F1: 0.44
0.45 Precision: 0.305 Recall: 0.72 F1: 0.429
0.5 Precision: 0.362 Recall: 0.68 F1: 0.472
0.55 Precision: 0.385 Recall: 0.6 F1: 0.469
0.6 Precision: 0.407 Recall: 0.44 F1: 0.423
0.65 Precision: 0.476 Recall: 0.4 F1: 0.435
0.7 Precision: 0.5 Recall: 0.4 F1: 0.444
0.75 Precision: 0.462 Recall: 0.24 F1: 0.316
0.8 Precision: 0.571 Recall: 0.16 F1: 0.25


In [42]:
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    accuracy_score,
    roc_auc_score
)

test_prob = best_model.predict_proba(X_test)[:, 1]

final_threshold = 0.50

test_pred = np.where(
    test_prob >= final_threshold,
    "Yes",
    "No"
)

print("Accuracy:", accuracy_score(y_test, test_pred))
print("ROC-AUC:", roc_auc_score(y_test, test_prob))
print()
print("Confusion Matrix:")
print(confusion_matrix(y_test, test_pred))
print()
print("Classification Report:")
print(classification_report(y_test, test_pred))

Accuracy: 0.675
ROC-AUC: 0.7692631578947369

Confusion Matrix:
[[64 31]
 [ 8 17]]

Classification Report:
              precision    recall  f1-score   support

          No       0.89      0.67      0.77        95
         Yes       0.35      0.68      0.47        25

    accuracy                           0.68       120
   macro avg       0.62      0.68      0.62       120
weighted avg       0.78      0.68      0.70       120



In [43]:
final_model = Pipeline([
    ("preprocessor", preprocessor),
    ("model", LogisticRegression(
        C=0.1,
        class_weight="balanced",
        max_iter=1000,
        random_state=42
    ))
])

final_model.fit(X_train_val, y_train_val)

,steps,"[('preprocessor', ...), ('model', ...)]"
,transform_input,None
,memory,None
,verbose,False
,transformers,"[('num', ...), ('cat', ...)]"
,remainder,'drop'
,sparse_threshold,0.3
,n_jobs,None
,transformer_weights,None
,verbose,False
,verbose_feature_names_out,True


In [44]:
import joblib

joblib.dump(
    final_model,
    "cloud_churn_final_pipeline.pkl"
)

['cloud_churn_final_pipeline.pkl']

In [45]:
joblib.dump(
    0.50,
    "cloud_churn_threshold.pkl"
)

['cloud_churn_threshold.pkl']